from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Text, BigInteger, Float
from . import app

#engine = create_engine(app_config["DATABASE_URL"])
engine = create_engine(app.config["SQLALCHEMY_DATABASE_URI"])
Base = declarative_base()
Session = sessionmaker(bind=engine)
session = Session()


# create the entries in the sql alchemy database by reading the csv 1 line at a time using csv dictreader
# import this so the table can create these entries
class Entry(Base):
    __tablename__ = "entries"
    Subject  = Column(String(1024), nullable=True)
    PASecureID = Column(BigInteger, primary_key=True)
    state_subject_year  = Column(String(1024), nullable=True)
    Local_Student_ID  = Column(String(1024), nullable=True)
    PVAAS = Column(Integer, nullable=True)
    Grade = Column(Integer, nullable=True)
    Tested_Year = Column(Integer, nullable=True)
    PASA_Record  = Column(String(1024), nullable=True)
    Ethnicity_Code = Column(Integer, nullable=True)
    IEP  = Column(String(1024), nullable=True)
    Economically_Disadvantaged  = Column(String(1024), nullable=True)
    Historically_Underperforming_Subgroup  = Column(String(1024), nullable=True)
    Scaled_Score = Column(Integer, nullable=True)
    Performance_Level_Code = Column(Integer, nullable=True)
    Performance_Level_Name  = Column(String(1024), nullable=True)
    Total_Raw_Score = Column(Integer, nullable=True)
    MultipleChoice_Raw_Score = Column(Integer, nullable=True)
    OpenEnded_Raw_Score = Column(Integer, nullable=True)
    Reporting_Category_1_Raw_Score = Column(Integer, nullable=True)
    Anchor_1_1 = Column(Integer, nullable=True)
    Anchor_1_2 = Column(Integer, nullable=True)
    Anchor_1_3 = Column(Integer, nullable=True)
    Anchor_1_4 = Column(Integer, nullable=True)
    Reporting_Category_2_Raw_Score = Column(Integer, nullable=True)
    Anchor_2_1 = Column(Integer, nullable=True)
    Anchor_2_2 = Column(Integer, nullable=True)
    Anchor_2_3 = Column(Integer, nullable=True)
    Anchor_2_4 = Column(Integer, nullable=True)
    Reporting_Category_3_Raw_Score = Column(Integer, nullable=True)
    Anchor_3_1 = Column(Integer, nullable=True)
    Anchor_3_2 = Column(Integer, nullable=True)
    Anchor_3_3 = Column(Integer, nullable=True)
    Anchor_3_4 = Column(Integer, nullable=True)
    Reporting_Category_4_Raw_Score = Column(Integer, nullable=True)
    Anchor_4_1 = Column(Integer, nullable=True)
    Anchor_4_2 = Column(Integer, nullable=True)
    Anchor_4_3 = Column(Integer, nullable=True)
    Anchor_4_4 = Column(Integer, nullable=True)
    Reporting_Category_5_Raw_Score = Column(Integer, nullable=True)
    Anchor_5_1 = Column(Integer, nullable=True)
    Anchor_5_2 = Column(Integer, nullable=True)
    Anchor_5_3 = Column(Integer, nullable=True)
    Anchor_5_4 = Column(Integer, nullable=True)
    Reporting_Category_6_Raw_Score = Column(Integer, nullable=True)
    Anchor_6_1 = Column(Integer, nullable=True)
    Anchor_6_2 = Column(Integer, nullable=True)
    Anchor_6_3 = Column(Integer, nullable=True)
    Anchor_6_4 = Column(Integer, nullable=True)
    Reporting_Category_7_Raw_Score = Column(Integer, nullable=True)
    Anchor_7_1 = Column(Integer, nullable=True)
    Anchor_7_2 = Column(Integer, nullable=True)
    Anchor_7_3 = Column(Integer, nullable=True)
    Anchor_7_4 = Column(Integer, nullable=True)
    Reporting_Category_8_Raw_Score = Column(Integer, nullable=True)
    Anchor_8_1 = Column(Integer, nullable=True)
    Anchor_8_2 = Column(Integer, nullable=True)
    Anchor_8_3 = Column(Integer, nullable=True)
    Anchor_8_4 = Column(Integer, nullable=True)
    Reporting_Category_9_Raw_Score = Column(Integer, nullable=True)
    Anchor_9_1 = Column(Integer, nullable=True)
    Anchor_9_2 = Column(Integer, nullable=True)
    Anchor_9_3 = Column(Integer, nullable=True)
    Anchor_9_4 = Column(Integer, nullable=True)
    Reporting_Category_10_Raw_Score = Column(Integer, nullable=True)
    Anchor_10_1 = Column(Integer, nullable=True)
    Anchor_10_2 = Column(Integer, nullable=True)
    Anchor_10_3 = Column(Integer, nullable=True)
    Anchor_10_4 = Column(Integer, nullable=True)
    Reporting_Category_1_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_2_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_3_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_4_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_5_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_6_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_7_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_8_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_9_Strength_Profile  = Column(String(1024), nullable=True)
    Reporting_Category_10_Strength_Profile  = Column(String(1024), nullable=True)
    Gender  = Column(String(1024), nullable=True)
    Title_I  = Column(String(1024), nullable=True)
    enrolled_after_Oct_1st  = Column(String(1024), nullable=True)
    enrolled_between_Octobers  = Column(String(1024), nullable=True) 



    
# Base.metadata.drop_all(engine) # learn about migrations
Base.metadata.create_all(engine)

